// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLMtkMar7BDI-9RjSx46TBLqR1eGSwbu8',
    appId: '1:152324579891:web:ea730d70ade78fda97b946',
    messagingSenderId: '152324579891',
    projectId: 'hackathon-project-jp',
    authDomain: 'hackathon-project-jp.firebaseapp.com',
    storageBucket: 'hackathon-project-jp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUHU2gY794Z4QlvuPy46qauRvmhPmOlHU',
    appId: '1:152324579891:android:5a14f9373fae606997b946',
    messagingSenderId: '152324579891',
    projectId: 'hackathon-project-jp',
    storageBucket: 'hackathon-project-jp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjdKzuwpcen4-dl1I4QBOZnUvuX7VHqU8',
    appId: '1:152324579891:ios:97b48ab8ab9b45b797b946',
    messagingSenderId: '152324579891',
    projectId: 'hackathon-project-jp',
    storageBucket: 'hackathon-project-jp.appspot.com',
    iosBundleId: 'com.example.projectJp',
  );
}
